# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cenk Cetinkaya Blog
email: mail@cenkcetinkaya.com
description: > # this means to ignore newlines until "baseurl:"
  About Coding
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cenkce.gihub.io" # the base hostname & protocol for your site
twitter_username: nullcappone
github_username:  cenkce

# Build settings
markdown: kramdown
